//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanThuoc.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int ID_ReceiptDetails { get; set; }
        public int ID_Medicine { get; set; }
        public int Amount { get; set; }
        public double Import_Pirce { get; set; }
        public Nullable<bool> Bill_Status { get; set; }
        public Nullable<int> Id_Unit { get; set; }
        public Nullable<double> toTalPrice { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
